const cards = [
  ["Create", "Generate an image from a prompt"],
  ["Library", "Your saved media assets and variants"],
  ["Instagram", "Connect an account to publish"],
  ["Calendar", "Schedule content with confidence"],
];
export default function Home() {
  return <main><aside><strong>instaHub</strong><span>Dashboard</span><span>Create</span><span>Library</span><span>Calendar</span><span>Settings</span></aside><section><header><div><p className="eyebrow">AI CREATOR STUDIO</p><h1>Make content worth posting.</h1><p className="muted">Generate, refine, publish, and schedule from one workspace.</p></div><button>Create image</button></header><div className="stats"><article><span>Assets</span><b>0</b></article><article><span>Scheduled</span><b>0</b></article><article><span>Instagram</span><b>Not connected</b></article></div><h2>Start here</h2><div className="grid">{cards.map(([title, desc]) => <article className="card" key={title}><h3>{title}</h3><p>{desc}</p></article>)}</div></section><style>{`main{display:grid;grid-template-columns:220px 1fr;min-height:100vh}aside{padding:28px 20px;border-right:1px solid #27272a;display:flex;flex-direction:column;gap:22px}aside strong{font-size:22px;color:#f472b6}aside span{color:#a1a1aa}section{max-width:1100px;width:100%;padding:60px;margin:auto}header{display:flex;justify-content:space-between;gap:24px;align-items:start}h1{font-size:clamp(36px,5vw,64px);margin:8px 0}.eyebrow{color:#f472b6;font-size:12px;letter-spacing:.14em}.muted,.card p{color:#a1a1aa}button{background:#ec4899;color:#fff;border:0;border-radius:10px;padding:12px 18px;font-weight:700}.stats,.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:42px 0}.grid{grid-template-columns:repeat(2,1fr);margin-top:16px}article{background:#18181b;border:1px solid #27272a;border-radius:14px;padding:20px}.stats span{display:block;color:#a1a1aa;margin-bottom:10px}.stats b{font-size:24px}@media(max-width:700px){main{display:block}aside{display:none}section{padding:32px 20px}.stats,.grid{grid-template-columns:1fr}header{display:block}button{margin-top:16px}}`}</style></main>;
}
