"use client";

import {FormEvent, useEffect, useState}from"react";
import {Icon, InlineNotice, PageHeader, StatusBadge} from "../../components/StudioUI";

type Provider={name:string;label:string;models:string[];capabilities:string[];enabled:boolean};type Connection={provider_name:string;label:string;is_connected:boolean;enabled:boolean};
const api=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";

export default function Providers(){
  const[providers,setProviders]=useState<Provider[]>([]),[connections,setConnections]=useState<Connection[]>([]),[selected,setSelected]=useState("openai"),[key,setKey]=useState(""),[message,setMessage]=useState(""),[tone,setTone]=useState<"info"|"success"|"error">("info"),[showKey,setShowKey]=useState(false),[loading,setLoading]=useState(true);
  const auth=()=>({token:localStorage.getItem("instahub_access_token"),workspace:localStorage.getItem("instahub_workspace_id")});
  async function load(){const{token,workspace}=auth();if(!token||!workspace){setMessage("Sign in and select a workspace first.");setTone("error");setLoading(false);return}const headers={Authorization:"Bearer "+token};const[p,c,w]=await Promise.all([fetch(api+"/v1/providers"),fetch(api+`/v1/workspaces/${workspace}/ai-providers`,{headers}),fetch(api+"/v1/workspaces",{headers})]);if(p.ok)setProviders(await p.json());if(c.ok)setConnections(await c.json());if(w.ok){const rows=await w.json();const current=rows.find((x:{id:string})=>x.id===workspace);if(current)setSelected(current.default_provider)}setLoading(false)}useEffect(()=>{load()},[]);
  async function connect(e:FormEvent){e.preventDefault();const{token,workspace}=auth();const r=await fetch(api+`/v1/workspaces/${workspace}/ai-providers/openai`,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({api_key:key})});setMessage(r.ok?"OpenAI connected securely. It is ready for images, edits, and captions.":(await r.json()).detail??"Connection failed.");setTone(r.ok?"success":"error");if(r.ok){setKey("");setShowKey(false);load()}}
  async function choose(name:string){const{token,workspace}=auth();const r=await fetch(api+`/v1/workspaces/${workspace}/default-provider`,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({provider_name:name})});setMessage(r.ok?`${name} is now the default provider for new generations.`:(await r.json()).detail);setTone(r.ok?"success":"error");if(r.ok)setSelected(name)}

  return <main><div className="page providers-page">
    <PageHeader eyebrow="AI Connector Cloud" title="Bring your own" accent="creative intelligence." description="Connect provider accounts once, choose a workspace default, and keep the creation workflow independent from any single AI platform." actions={<button className="button" onClick={()=>setShowKey(value=>!value)}><Icon name="plus" size={16}/>{showKey?"Close":"Add connector"}</button>}/>
    {showKey&&<form className="card connect-panel" onSubmit={connect}><span className="provider-monogram">OA</span><div><h2>Connect OpenAI</h2><p>Unlock image generation, prompt editing, captions, and hashtags. Your key is encrypted at rest.</p></div><label className="field"><span className="field-label">API key</span><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="sk-…" required autoFocus/></label><button className="button"><Icon name="shield" size={15}/>Connect securely</button></form>}
    {message&&<div className="provider-message"><InlineNotice tone={tone}>{message}</InlineNotice></div>}
    <div className="provider-summary"><article><span><Icon name="plug"/></span><div><b>{connections.filter(item=>item.is_connected).length}</b><small>Connected providers</small></div></article><article><span><Icon name="sparkles"/></span><div><b>{selected||"None"}</b><small>Workspace default</small></div></article><article><span><Icon name="shield"/></span><div><b>Encrypted</b><small>Provider credentials</small></div></article></div>
    <div className="section-heading"><div><h2>Provider registry</h2><p>Capabilities are routed through one connector layer</p></div><span className="registry-count">{providers.length} providers</span></div>
    <section className="provider-grid">{loading?[1,2,3,4].map(value=><i className="provider-skeleton" key={value}/>):providers.map(provider=>{const connected=connections.find(item=>item.provider_name===provider.name)?.is_connected;const isDefault=selected===provider.name;return <article className={isDefault?"provider-card card selected":"provider-card card"} key={provider.name}><div className="provider-top"><span className="provider-monogram">{provider.label.slice(0,2).toUpperCase()}</span><StatusBadge status={connected?"Connected":provider.enabled?"Available":"Coming soon"}/></div><div><h2>{provider.label}</h2><p>{provider.capabilities.length?provider.capabilities.map(value=>value.replaceAll("_"," ")).join(" · "):"Future media capabilities"}</p></div><div className="capabilities">{provider.capabilities.slice(0,4).map(value=><span key={value}>{value.replaceAll("_"," ")}</span>)}</div><div className="model-row"><span>Models</span><small>{provider.models.join(" / ")||"Configured when enabled"}</small></div><button className={isDefault?"button secondary full":"button ghost full"} disabled={!provider.enabled||!connected||isDefault} onClick={()=>choose(provider.name)}>{isDefault?<><Icon name="check" size={15}/>Default provider</>:connected?<><Icon name="sparkles" size={15}/>Set as default</>:provider.name==="openai"?<><Icon name="plug" size={15}/>Connect above</>:"Not connected"}</button></article>})}</section>
  </div><style>{`
    .connect-panel{display:grid;grid-template-columns:auto 1fr minmax(240px,.7fr) auto;gap:14px;align-items:center;margin-bottom:14px;padding:17px}.connect-panel h2{margin:0 0 5px;font-size:14px}.connect-panel p{margin:0;color:var(--muted);font-size:10px;line-height:1.5}.provider-monogram{display:grid;place-items:center;width:43px;height:43px;border:1px solid rgba(155,122,255,.18);border-radius:12px;background:linear-gradient(145deg,rgba(155,122,255,.17),rgba(255,92,157,.07));color:#d6c9ff;font-size:11px;font-weight:900}.provider-message{margin:10px 0}.provider-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.provider-summary article{display:flex;gap:12px;align-items:center;padding:15px;border:1px solid var(--line);border-radius:13px;background:rgba(255,255,255,.018)}.provider-summary article>span{display:grid;place-items:center;width:36px;height:36px;border-radius:10px;background:#24212c;color:#bda9ef}.provider-summary article>div{display:grid;gap:2px}.provider-summary b{font-size:13px;text-transform:capitalize}.provider-summary small,.registry-count{color:var(--muted);font-size:9px}.provider-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.provider-card{display:grid;gap:20px;padding:20px}.provider-card.selected{border-color:rgba(155,122,255,.42);box-shadow:inset 0 2px 0 rgba(155,122,255,.55)}.provider-top{display:flex;justify-content:space-between;align-items:center}.provider-card h2{margin:0 0 6px;font-size:21px}.provider-card p{min-height:34px;margin:0;color:var(--muted);font-size:10px;line-height:1.55;text-transform:capitalize}.capabilities{display:flex;flex-wrap:wrap;gap:5px}.capabilities span{padding:5px 7px;border:1px solid var(--line);border-radius:7px;color:#aaa4b1;font-size:8px;text-transform:capitalize}.model-row{display:flex;justify-content:space-between;gap:12px;padding-top:13px;border-top:1px solid var(--line)}.model-row span{color:var(--muted-2);font-size:9px}.model-row small{color:#aaa4b1;font-size:9px;text-align:right}.provider-skeleton{min-height:320px;border-radius:16px;background:linear-gradient(100deg,#111219 30%,#191a22 50%,#111219 70%);background-size:300%;animation:shimmer 1.4s infinite}
    @media(max-width:1000px){.connect-panel{grid-template-columns:auto 1fr}.connect-panel .field,.connect-panel .button{grid-column:1/-1}}@media(max-width:650px){.provider-grid,.provider-summary{grid-template-columns:1fr}.provider-summary{gap:6px}.provider-summary article{padding:11px}.connect-panel{grid-template-columns:1fr}.connect-panel .provider-monogram{display:none}}
  `}</style></main>;
}
