"use client";

import Link from "next/link";
import {useEffect, useState} from "react";
import {Icon, InlineNotice, PageHeader, StatusBadge} from "../../components/StudioUI";
const api=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";

export default function Instagram(){
  const[status,setStatus]=useState<{account_name:string;account_type?:string;expires_at?:string}|null|undefined>(undefined),[error,setError]=useState("");
  const auth=()=>({token:localStorage.getItem("instahub_access_token"),workspace:localStorage.getItem("instahub_workspace_id")});
  useEffect(()=>{const{token,workspace}=auth();if(!token||!workspace){setStatus(null);return}fetch(api+"/v1/instagram/status?workspace_id="+workspace,{headers:{Authorization:"Bearer "+token}}).then(r=>r.ok?r.json():null).then(setStatus)},[]);
  async function connect(){const{token,workspace}=auth();if(!token||!workspace){setError("Sign in and select a workspace first.");return}const r=await fetch(api+"/v1/instagram/connect?workspace_id="+workspace,{headers:{Authorization:"Bearer "+token}});if(!r.ok){setError("Instagram OAuth is not configured for this environment.");return}window.location.assign((await r.json()).authorization_url)}
  return <main><div className="page narrow social-page">
    <PageHeader eyebrow="Social Connector" title="Connect" accent="Instagram." description="Link a professional Instagram account through Meta OAuth, then publish studio assets directly or schedule them for later." actions={<Link href="/publish" className="button secondary"><Icon name="send" size={16}/>Publish desk</Link>}/>
    <section className="social-connect-card card">
      <div className="social-visual instagram-visual"><span><Icon name="instagram" size={34}/></span><small>Meta platform</small></div>
      <div className="connection-content">
        <div className="connection-heading"><div><p className="card-kicker">ACCOUNT CONNECTION</p><h2>{status?`@${status.account_name}`:"Instagram Professional"}</h2></div><StatusBadge status={status===undefined?"Checking":status?"Connected":"Not connected"}/></div>
        {status?<><p>Your {status.account_type?.toLowerCase()??"professional"} account is ready for image publishing and scheduled posts.</p><div className="account-details"><span><Icon name="check" size={14}/>Publishing enabled</span><span><Icon name="clock" size={14}/>Token refresh managed</span><span><Icon name="shield" size={14}/>Credentials encrypted</span></div>{status.expires_at&&<small className="expiry">Current token expiry: {new Date(status.expires_at).toLocaleDateString()}</small>}<button className="button secondary" onClick={connect}><Icon name="refresh" size={15}/>Reconnect account</button></>:<><p>Connect the Facebook Page linked to your Instagram business or creator account. Personal Instagram accounts are not eligible for API publishing.</p><button className="button connect-button" onClick={connect} disabled={status===undefined}><Icon name="instagram" size={16}/>{status===undefined?"Checking connection…":"Continue with Meta"}<Icon name="external" size={14}/></button></>}
        {error&&<InlineNotice tone="error">{error}</InlineNotice>}
      </div>
    </section>
    <div className="connection-steps"><article><span>01</span><div><b>Authorize with Meta</b><p>Review the official permission screen and choose the correct business account.</p></div></article><article><span>02</span><div><b>We validate eligibility</b><p>The API confirms the account type, linked Page, and available publishing permissions.</p></div></article><article><span>03</span><div><b>Publish with confidence</b><p>Track queued, published, or failed attempts from the publish desk.</p></div></article></div>
  </div><style>{socialStyles}</style></main>;
}

const socialStyles=`
  .social-connect-card{display:grid;grid-template-columns:minmax(240px,.68fr) minmax(0,1.32fr);overflow:hidden}.social-visual{position:relative;display:grid;place-items:center;align-content:center;gap:15px;min-height:430px;border-right:1px solid var(--line);background:radial-gradient(circle at 50% 45%,rgba(255,92,157,.2),transparent 10rem),linear-gradient(145deg,#24131e,#121018)}.social-visual>span{display:grid;place-items:center;width:86px;height:86px;border:1px solid rgba(255,255,255,.15);border-radius:27px;background:linear-gradient(145deg,#ff765d,#b14cff 60%,#6238c5);box-shadow:0 25px 60px rgba(154,61,158,.3)}.social-visual small{color:#bfa9b9;font-size:9px;letter-spacing:.15em;text-transform:uppercase}.connection-content{display:grid;align-content:center;gap:18px;padding:36px}.connection-heading{display:flex;justify-content:space-between;gap:15px;align-items:flex-start}.connection-heading h2{margin:0;font-size:25px}.card-kicker{margin:0 0 5px;color:var(--pink);font-size:9px;font-weight:800;letter-spacing:.15em}.connection-content>p{margin:0;color:var(--muted);font-size:12px;line-height:1.65}.connection-content>.button{width:fit-content}.connect-button{min-width:210px}.account-details{display:grid;gap:8px}.account-details span{display:flex;gap:8px;align-items:center;color:#bbb5c0;font-size:10px}.account-details svg{color:var(--mint)}.expiry{color:var(--muted-2);font-size:9px}.connection-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:14px}.connection-steps article{display:flex;gap:12px;padding:16px;border:1px solid var(--line);border-radius:13px;background:rgba(255,255,255,.017)}.connection-steps article>span{color:var(--pink);font-size:9px;font-weight:900}.connection-steps article div{display:grid;gap:5px}.connection-steps b{font-size:11px}.connection-steps p{margin:0;color:var(--muted);font-size:9px;line-height:1.5}@media(max-width:760px){.social-connect-card{grid-template-columns:1fr}.social-visual{min-height:210px;border-right:0;border-bottom:1px solid var(--line)}.connection-content{padding:24px 19px}.connection-steps{grid-template-columns:1fr}}
`;
