"use client";

import Link from "next/link";
import {useState} from "react";
import {Icon, InlineNotice, PageHeader, StatusBadge} from "../../components/StudioUI";
const api=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";

export default function Pinterest(){
  const[msg,setMsg]=useState("");
  async function connect(){const token=localStorage.getItem("instahub_access_token"),workspace=localStorage.getItem("instahub_workspace_id");if(!token||!workspace){setMsg("Sign in and select a workspace first.");return}const r=await fetch(api+"/v1/pinterest/connect?workspace_id="+workspace,{headers:{Authorization:"Bearer "+token}});if(!r.ok){setMsg("Pinterest OAuth is not configured for this environment.");return}location.assign((await r.json()).authorization_url)}
  return <main><div className="page narrow pinterest-page">
    <PageHeader eyebrow="Social Connector" title="Connect" accent="Pinterest." description="Turn generated assets into Pins, choose the right board, and schedule evergreen content from the same studio." actions={<Link href="/publish" className="button secondary"><Icon name="send" size={16}/>Publish desk</Link>}/>
    <section className="social-connect-card card">
      <div className="social-visual"><span><Icon name="pinterest" size={37}/></span><small>Discovery platform</small></div>
      <div className="connection-content"><div className="connection-heading"><div><p className="card-kicker">ACCOUNT CONNECTION</p><h2>Pinterest Business</h2></div><StatusBadge status="OAuth ready"/></div><p>Authorize your Pinterest account, then select any accessible board while publishing or scheduling a Pin.</p><div className="account-details"><span><Icon name="check" size={14}/>Board selection</span><span><Icon name="check" size={14}/>Pin title and description</span><span><Icon name="shield" size={14}/>Encrypted access token</span></div><button className="button connect-button" onClick={connect}><Icon name="pinterest" size={16}/>Continue with Pinterest<Icon name="external" size={14}/></button>{msg&&<InlineNotice tone="error">{msg}</InlineNotice>}</div>
    </section>
    <div className="connection-steps"><article><span>01</span><div><b>Authorize Pinterest</b><p>Use the official OAuth screen and approve access to your boards and Pins.</p></div></article><article><span>02</span><div><b>Choose a board</b><p>Your available boards appear in the publish and scheduling workflows.</p></div></article><article><span>03</span><div><b>Publish evergreen content</b><p>Add a searchable title, caption, and media asset for each Pin.</p></div></article></div>
  </div><style>{`
    .social-connect-card{display:grid;grid-template-columns:minmax(240px,.68fr) minmax(0,1.32fr);overflow:hidden}.social-visual{position:relative;display:grid;place-items:center;align-content:center;gap:15px;min-height:430px;border-right:1px solid var(--line);background:radial-gradient(circle at 50% 45%,rgba(224,33,48,.2),transparent 10rem),linear-gradient(145deg,#2b1014,#121014)}.social-visual>span{display:grid;place-items:center;width:86px;height:86px;border:1px solid rgba(255,255,255,.15);border-radius:27px;background:linear-gradient(145deg,#e92335,#a60e1b);box-shadow:0 25px 60px rgba(170,24,37,.3)}.social-visual small{color:#c2a7a9;font-size:9px;letter-spacing:.15em;text-transform:uppercase}.connection-content{display:grid;align-content:center;gap:18px;padding:36px}.connection-heading{display:flex;justify-content:space-between;gap:15px;align-items:flex-start}.connection-heading h2{margin:0;font-size:25px}.card-kicker{margin:0 0 5px;color:#ef6572;font-size:9px;font-weight:800;letter-spacing:.15em}.connection-content>p{margin:0;color:var(--muted);font-size:12px;line-height:1.65}.connection-content>.button{width:fit-content}.connect-button{min-width:225px}.account-details{display:grid;gap:8px}.account-details span{display:flex;gap:8px;align-items:center;color:#bbb5c0;font-size:10px}.account-details svg{color:var(--mint)}.connection-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:14px}.connection-steps article{display:flex;gap:12px;padding:16px;border:1px solid var(--line);border-radius:13px;background:rgba(255,255,255,.017)}.connection-steps article>span{color:#ef6572;font-size:9px;font-weight:900}.connection-steps article div{display:grid;gap:5px}.connection-steps b{font-size:11px}.connection-steps p{margin:0;color:var(--muted);font-size:9px;line-height:1.5}@media(max-width:760px){.social-connect-card{grid-template-columns:1fr}.social-visual{min-height:210px;border-right:0;border-bottom:1px solid var(--line)}.connection-content{padding:24px 19px}.connection-steps{grid-template-columns:1fr}}
  `}</style></main>;
}
