"use client";

import Link from "next/link";
import {FormEvent, useEffect, useMemo, useState}from"react";
import {EmptyState, Icon, InlineNotice, PageHeader, StatusBadge} from "../../components/StudioUI";

type Asset={id:string;delivery_url:string};type Post={id:string;media_asset_id:string;caption:string;platform:string;scheduled_at:string;status:string};type Board={id:string;name:string};
const api=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";

export default function Schedule(){
  const[assets,setAssets]=useState<Asset[]>([]),[posts,setPosts]=useState<Post[]>([]),[asset,setAsset]=useState(""),[caption,setCaption]=useState(""),[platform,setPlatform]=useState("instagram"),[time,setTime]=useState(""),[boards,setBoards]=useState<Board[]>([]),[board,setBoard]=useState(""),[message,setMessage]=useState(""),[tone,setTone]=useState<"info"|"success"|"error">("info"),[editId,setEditId]=useState(""),[editTime,setEditTime]=useState("");
  const auth=()=>({token:localStorage.getItem("instahub_access_token"),workspace:localStorage.getItem("instahub_workspace_id")});
  const timezone=useMemo(()=>Intl.DateTimeFormat().resolvedOptions().timeZone,[]);
  async function load(){const{token,workspace}=auth();if(!token||!workspace){setMessage("Sign in and select a workspace first.");setTone("error");return}const headers={Authorization:"Bearer "+token};const[a,p]=await Promise.all([fetch(api+`/v1/workspaces/${workspace}/assets`,{headers}),fetch(api+`/v1/workspaces/${workspace}/scheduled-posts`,{headers})]);if(a.ok){const values=await a.json();setAssets(values);if(values[0]&&!asset)setAsset(values[0].id)}if(p.ok)setPosts(await p.json())}
  useEffect(()=>{load()},[]);useEffect(()=>{if(platform!=="pinterest")return;const{token,workspace}=auth();if(token&&workspace)fetch(api+`/v1/pinterest/boards?workspace_id=${workspace}`,{headers:{Authorization:"Bearer "+token}}).then(r=>r.ok?r.json():[]).then(setBoards)},[platform]);
  async function submit(e:FormEvent){e.preventDefault();const{token,workspace}=auth();if(!token||!workspace)return;const r=await fetch(api+"/v1/scheduled-posts",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({workspace_id:workspace,media_asset_id:asset,caption,platform,scheduled_at:new Date(time).toISOString(),board_id:platform==="pinterest"?board:null})});const data=await r.json();setMessage(r.ok?"Post scheduled successfully in your local timezone.":data.detail??"Could not schedule post.");setTone(r.ok?"success":"error");if(r.ok){setCaption("");setTime("");load()}}
  async function cancel(id:string){const{token}=auth();const r=await fetch(api+`/v1/scheduled-posts/${id}`,{method:"DELETE",headers:{Authorization:"Bearer "+token}});setMessage(r.ok?"Scheduled post cancelled.":"Could not cancel this post.");setTone(r.ok?"success":"error");load()}
  async function saveMove(id:string){if(!editTime)return;const{token}=auth();const r=await fetch(api+`/v1/scheduled-posts/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({scheduled_at:new Date(editTime).toISOString()})});setMessage(r.ok?"Publishing time updated.":"Could not update the publishing time.");setTone(r.ok?"success":"error");if(r.ok)setEditId("");load()}
  function startEdit(post:Post){setEditId(post.id);const date=new Date(post.scheduled_at);const local=new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);setEditTime(local)}

  return <main><div className="page schedule-page">
    <PageHeader eyebrow="Content Calendar" title="Plan the rhythm." accent="Keep momentum." description={`Schedule in ${timezone}. Times are converted safely for background publishing and automatic retries.`} actions={<Link href="/publish" className="button secondary"><Icon name="send" size={16}/>Publish now</Link>}/>
    <div className="schedule-layout">
      <form className="card schedule-form" onSubmit={submit}>
        <div className="card-header"><div><p className="card-kicker">NEW POST</p><h2>Schedule content</h2></div><span className="timezone"><Icon name="clock" size={13}/>{timezone}</span></div>
        <div className="card-body stack">
          <div className="field"><span className="field-label">Channel</span><div className="channel-switch">{["instagram","pinterest"].map(value=><button type="button" className={platform===value?"active":""} onClick={()=>setPlatform(value)} key={value}><Icon name={value==="instagram"?"instagram":"pinterest"} size={16}/>{value}</button>)}</div></div>
          <div className="field"><span className="field-label">Choose media <small>{assets.length} assets</small></span>{assets.length?<div className="schedule-assets">{assets.map((item,index)=><button type="button" className={asset===item.id?"media-tile selected":"media-tile"} onClick={()=>setAsset(item.id)} key={item.id} aria-label={`Select asset ${index+1}`}><img src={item.delivery_url} alt={`Asset ${index+1}`}/></button>)}</div>:<Link href="/" className="inline-empty"><Icon name="plus" size={14}/>Create your first asset</Link>}</div>
          {platform==="pinterest"&&<label className="field"><span className="field-label">Pinterest board</span><select value={board} onChange={e=>setBoard(e.target.value)} required><option value="">Choose a board</option>{boards.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label>}
          <label className="field"><span className="field-label">Caption <small className="char-count">{caption.length}/2,200</small></span><textarea value={caption} onChange={e=>setCaption(e.target.value)} maxLength={2200} placeholder="Write a caption, or add one later…"/></label>
          <label className="field"><span className="field-label">Local date & time</span><input type="datetime-local" value={time} onChange={e=>setTime(e.target.value)} min={new Date().toISOString().slice(0,16)} required/></label>
          <button className="button full" disabled={!asset||!time||(platform==="pinterest"&&!board)}><Icon name="calendar" size={16}/>Schedule post</button>
          {message&&<InlineNotice tone={tone}>{message}</InlineNotice>}
        </div>
      </form>

      <section className="card upcoming-card">
        <div className="card-header"><div><p className="card-kicker">QUEUE</p><h2>Upcoming posts</h2></div><span className="queue-count">{posts.length} scheduled</span></div>
        {posts.length?<div className="upcoming-list">{posts.map((post,index)=>{const media=assets.find(item=>item.id===post.media_asset_id);return <article className="schedule-row" key={post.id}>{media?<img src={media.delivery_url} alt="Scheduled media"/>:<span className="media-placeholder"><Icon name="image"/></span>}<div className="post-details"><div><Icon name={post.platform==="instagram"?"instagram":"pinterest"} size={13}/><b>{post.platform}</b><StatusBadge status={post.status}/></div><time dateTime={post.scheduled_at}>{new Date(post.scheduled_at).toLocaleString(undefined,{weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</time><p>{post.caption||"No caption added"}</p>{editId===post.id&&<div className="edit-time"><input type="datetime-local" value={editTime} onChange={e=>setEditTime(e.target.value)}/><button className="button" onClick={()=>saveMove(post.id)}>Save</button><button className="button ghost" onClick={()=>setEditId("")}>Close</button></div>}</div><div className="row-actions"><button className="icon-button" onClick={()=>startEdit(post)} title="Edit schedule" aria-label="Edit schedule"><Icon name="calendar" size={15}/></button><button className="icon-button danger-icon" onClick={()=>cancel(post.id)} title="Cancel post" aria-label="Cancel scheduled post"><Icon name="trash" size={15}/></button></div></article>})}</div>:<EmptyState icon="calendar" title="Your calendar is clear" description="Schedule the next great post and it will appear here with its channel, status, and local publish time."/>}
      </section>
    </div>
  </div><style>{`
    .schedule-layout{display:grid;grid-template-columns:minmax(360px,.8fr) minmax(0,1.2fr);gap:18px;align-items:start}.schedule-form{position:sticky;top:24px}.card-kicker{margin:0 0 4px;color:var(--pink);font-size:9px;font-weight:800;letter-spacing:.15em}.timezone{display:flex;align-items:center;gap:5px;color:var(--muted);font-size:9px}.channel-switch{display:grid;grid-template-columns:1fr 1fr;gap:7px}.channel-switch button{display:flex;justify-content:center;align-items:center;gap:7px;padding:10px;border:1px solid var(--line);border-radius:10px;background:#0c0d12;color:var(--muted);font-size:10px;text-transform:capitalize}.channel-switch button.active{border-color:rgba(255,92,157,.35);background:rgba(255,92,157,.065);color:#fff}.schedule-assets{display:grid;grid-template-columns:repeat(6,1fr);gap:6px;max-height:180px;overflow:auto}.inline-empty{display:flex;align-items:center;gap:6px;padding:12px;border:1px dashed var(--line-strong);border-radius:10px;color:#c3b7df;font-size:10px;text-decoration:none}.schedule-form textarea{min-height:90px}.upcoming-card{overflow:hidden}.queue-count{color:var(--muted);font-size:10px}.upcoming-list{display:grid}.schedule-row{display:grid;grid-template-columns:74px 1fr auto;gap:14px;align-items:start;padding:14px 16px;border-bottom:1px solid var(--line)}.schedule-row:last-child{border:0}.schedule-row>img,.media-placeholder{display:grid;place-items:center;width:74px;height:74px;border-radius:11px;background:#0b0c10;object-fit:cover;color:var(--muted)}.post-details{min-width:0}.post-details>div:first-child{display:flex;gap:6px;align-items:center}.post-details b{color:#c9c4cf;font-size:9px;letter-spacing:.08em;text-transform:uppercase}.post-details time{display:block;margin:8px 0 5px;color:#fff;font-size:13px;font-weight:650}.post-details p{overflow:hidden;margin:0;color:var(--muted);font-size:10px;text-overflow:ellipsis;white-space:nowrap}.row-actions{display:flex;gap:5px}.danger-icon:hover{border-color:rgba(255,130,149,.25);color:var(--danger)}.edit-time{display:grid!important;grid-template-columns:1fr auto auto;gap:6px!important;margin-top:10px}.edit-time input{padding:8px;font-size:10px}.edit-time .button{min-height:34px;padding:7px 10px;font-size:9px}
    @media(max-width:1050px){.schedule-layout{grid-template-columns:1fr}.schedule-form{position:static}}@media(max-width:620px){.schedule-assets{grid-template-columns:repeat(5,1fr)}.schedule-row{grid-template-columns:58px 1fr}.schedule-row>img,.media-placeholder{width:58px;height:58px}.row-actions{grid-column:2}.edit-time{grid-template-columns:1fr 1fr}.edit-time input{grid-column:1/-1}}
  `}</style></main>;
}
