"use client";

import {FormEvent, useEffect, useState}from"react";
import {EmptyState, Icon, InlineNotice, PageHeader, StatusBadge} from "../../components/StudioUI";
type Brand={id:string;name:string;tone:string;visual_dna:Record<string,string>;reference_asset_ids:string[]};type Asset={id:string;delivery_url:string};
const api=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";

export default function BrandStudio(){
  const[name,setName]=useState(""),[tone,setTone]=useState("Bold & editorial"),[colors,setColors]=useState("#ff5c8a, #191126, #f7e8d0"),[style,setStyle]=useState("Glossy product photography, dramatic soft shadows"),[status,setStatus]=useState(""),[statusTone,setStatusTone]=useState<"info"|"success"|"error">("info"),[brands,setBrands]=useState<Brand[]>([]),[assets,setAssets]=useState<Asset[]>([]),[refs,setRefs]=useState<string[]>([]),[active,setActive]=useState(""),[persona,setPersona]=useState(""),[role,setRole]=useState("Creator"),[appearance,setAppearance]=useState(""),[memory,setMemory]=useState("");
  const auth=()=>({token:localStorage.getItem("instahub_access_token"),workspace:localStorage.getItem("instahub_workspace_id")});
  async function load(){const{token,workspace}=auth();if(!token||!workspace)return;const headers={Authorization:"Bearer "+token};const[b,a]=await Promise.all([fetch(api+`/v1/workspaces/${workspace}/brands`,{headers}),fetch(api+`/v1/workspaces/${workspace}/assets`,{headers})]);if(b.ok){const rows=await b.json();setBrands(rows);if(rows[0]&&!active)setActive(rows[0].id)}if(a.ok)setAssets(await a.json())}useEffect(()=>{load()},[]);
  async function save(e:FormEvent){e.preventDefault();const{token,workspace}=auth();if(!token||!workspace){setStatus("Sign in and select a workspace first.");setStatusTone("error");return}const r=await fetch(api+`/v1/workspaces/${workspace}/brands`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({name,tone,visual_dna:{palette:colors,art_direction:style},prompt_defaults:{consistency:"Keep palette, lighting and visual motifs recognizable"},reference_asset_ids:refs})});if(r.ok){const item=await r.json();setActive(item.id);setStatus("Creative DNA saved. It is now available in the image studio.");setStatusTone("success");load()}else{setStatus((await r.json()).detail??"Could not save your brand profile.");setStatusTone("error")}}
  async function savePersona(e:FormEvent){e.preventDefault();const{token}=auth();if(!active){setStatus("Choose or save a brand before adding a persona.");setStatusTone("error");return}const r=await fetch(api+`/v1/brands/${active}/personas`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({name:persona,role,appearance:{description:appearance},consistency_memory:memory})});setStatus(r.ok?"Persona saved to this brand’s consistency memory.":(await r.json()).detail??"Could not save persona.");setStatusTone(r.ok?"success":"error");if(r.ok){setPersona("");setAppearance("");setMemory("")}}
  function toggle(id:string){setRefs(values=>values.includes(id)?values.filter(value=>value!==id):[...values,id].slice(-12))}

  return <main><div className="page brand-page">
    <PageHeader eyebrow="Brand Studio" title="Make every post" accent="unmistakably yours." description="Save the visual rules, voice, references, and recurring characters that keep every generation in the same creative world." actions={<StatusBadge status={`${brands.length} profiles`}/>}/>
    {status&&<div className="brand-notice"><InlineNotice tone={statusTone}>{status}</InlineNotice></div>}
    <div className="brand-layout">
      <aside className="card profile-sidebar">
        <div className="card-header"><h2>Brand profiles</h2><button className="icon-button" onClick={()=>{setActive("");setName("");setRefs([])}} title="New profile" aria-label="New brand profile"><Icon name="plus" size={15}/></button></div>
        {brands.length?<div className="profile-list">{brands.map((brand,index)=><button className={active===brand.id?"active":""} onClick={()=>setActive(brand.id)} key={brand.id}><span className={`profile-swatch swatch-${index%4}`}>{brand.name.slice(0,2).toUpperCase()}</span><div><b>{brand.name}</b><small>{brand.tone}</small></div>{active===brand.id&&<Icon name="check" size={14}/>}</button>)}</div>:<EmptyState icon="palette" title="No profiles yet" description="Save creative DNA to keep future content consistent."/>}
        <div className="profile-tip"><Icon name="sparkles" size={15}/><p><b>Consistency compounds.</b> Use the same profile for a campaign to keep palette, lighting, and voice aligned.</p></div>
      </aside>

      <div className="brand-forms">
        <form className="card" onSubmit={save}>
          <div className="card-header"><div><p className="card-kicker">01 · CREATIVE DNA</p><h2>Visual and verbal identity</h2></div><Icon name="palette" size={19}/></div>
          <div className="card-body stack">
            <div className="two-fields"><label className="field"><span className="field-label">Brand name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nova House" required/></label><label className="field"><span className="field-label">Voice</span><select value={tone} onChange={e=>setTone(e.target.value)}><option>Bold & editorial</option><option>Warm & human</option><option>Minimal & premium</option><option>Playful & high-energy</option></select></label></div>
            <label className="field"><span className="field-label">Signature palette <small className="field-hint">Names or hex values</small></span><input value={colors} onChange={e=>setColors(e.target.value)}/><span className="palette-preview">{colors.split(",").slice(0,6).map((color,index)=><i style={{background:color.trim()}} key={index}/>)}</span></label>
            <label className="field"><span className="field-label">Visual direction</span><textarea value={style} onChange={e=>setStyle(e.target.value)} placeholder="Describe lighting, composition, texture, camera, and mood…"/></label>
            <div className="field"><span className="field-label">Reference images <small>{refs.length}/12 selected</small></span>{assets.length?<div className="reference-grid">{assets.slice(0,12).map((asset,index)=><button type="button" className={refs.includes(asset.id)?"media-tile selected":"media-tile"} onClick={()=>toggle(asset.id)} key={asset.id} aria-label={`Select reference ${index+1}`}><img src={asset.delivery_url} alt={`Brand reference ${index+1}`}/></button>)}</div>:<div className="reference-empty"><Icon name="image" size={16}/>Create images first to use visual references.</div>}</div>
            <button className="button full"><Icon name="check" size={16}/>Save creative DNA</button>
          </div>
        </form>

        <form className="card persona-card" onSubmit={savePersona}>
          <div className="card-header"><div><p className="card-kicker">02 · PERSONA MEMORY</p><h2>Recurring creator or character</h2></div><Icon name="layers" size={19}/></div>
          <div className="card-body stack"><div className="persona-intro"><span><Icon name="sparkles" size={18}/></span><p>Capture the details that should not drift between posts. Persona memory is attached to the selected brand profile.</p></div><div className="two-fields"><label className="field"><span className="field-label">Persona name</span><input value={persona} onChange={e=>setPersona(e.target.value)} placeholder="Mara" required/></label><label className="field"><span className="field-label">Role</span><input value={role} onChange={e=>setRole(e.target.value)} placeholder="Creator"/></label></div><label className="field"><span className="field-label">Appearance</span><textarea value={appearance} onChange={e=>setAppearance(e.target.value)} placeholder="Face, hair, wardrobe, distinguishing details…"/></label><label className="field"><span className="field-label">Consistency rules</span><textarea value={memory} onChange={e=>setMemory(e.target.value)} placeholder="Details that should never drift between posts…"/></label><button className="button secondary full" disabled={!active}><Icon name="layers" size={16}/>Save persona to profile</button></div>
        </form>
      </div>
    </div>
  </div><style>{`
    .brand-notice{margin-bottom:14px}.brand-layout{display:grid;grid-template-columns:260px minmax(0,1fr);gap:18px;align-items:start}.profile-sidebar{position:sticky;top:24px;overflow:hidden}.profile-list{display:grid;padding:8px}.profile-list button{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;padding:9px;border:1px solid transparent;border-radius:11px;background:transparent;color:var(--muted);text-align:left}.profile-list button:hover{background:rgba(255,255,255,.03)}.profile-list button.active{border-color:rgba(255,92,157,.15);background:rgba(255,92,157,.06);color:var(--pink-soft)}.profile-swatch{display:grid;place-items:center;width:36px;height:36px;border-radius:10px;background:#322332;color:#ffc4d7;font-size:9px;font-weight:900}.swatch-1{background:#202d3a;color:#a9d9ff}.swatch-2{background:#273129;color:#b6eab9}.swatch-3{background:#342c21;color:#f0d09a}.profile-list button>div{display:grid;gap:2px}.profile-list b{color:#ded9e2;font-size:10px}.profile-list small{font-size:8px}.profile-tip{display:flex;gap:9px;margin:8px;padding:12px;border:1px solid rgba(155,122,255,.11);border-radius:10px;background:rgba(155,122,255,.04);color:#b8a5e4}.profile-tip svg{flex:0 0 auto}.profile-tip p{margin:0;color:var(--muted);font-size:9px;line-height:1.5}.profile-tip b{display:block;margin-bottom:3px;color:#c8bedc}.brand-forms{display:grid;gap:18px}.card-kicker{margin:0 0 4px;color:var(--pink);font-size:9px;font-weight:800;letter-spacing:.15em}.card-header>svg{color:#8d849a}.two-fields{display:grid;grid-template-columns:1fr 1fr;gap:10px}.palette-preview{display:flex;gap:5px}.palette-preview i{width:25px;height:25px;border:2px solid #fff1;border-radius:8px;background:#333}.reference-grid{display:grid;grid-template-columns:repeat(8,1fr);gap:6px}.reference-empty{display:flex;align-items:center;gap:7px;padding:12px;border:1px dashed var(--line-strong);border-radius:10px;color:var(--muted);font-size:9px}.persona-card textarea{min-height:85px}.persona-intro{display:flex;gap:10px;align-items:center;padding:12px;border:1px solid rgba(119,220,247,.1);border-radius:11px;background:rgba(119,220,247,.035)}.persona-intro>span{display:grid;place-items:center;flex:0 0 auto;width:36px;height:36px;border-radius:10px;background:#222633;color:var(--cyan)}.persona-intro p{margin:0;color:var(--muted);font-size:9px;line-height:1.55}
    @media(max-width:1050px){.brand-layout{grid-template-columns:1fr}.profile-sidebar{position:static}.profile-list{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){.profile-list{grid-template-columns:1fr 1fr}.two-fields{grid-template-columns:1fr}.reference-grid{grid-template-columns:repeat(5,1fr)}}
  `}</style></main>;
}
