import Link from "next/link";
import {Icon, PageHeader, StatusBadge} from "../../components/StudioUI";

export default function VideoStudio(){
  return <main><div className="page video-page">
    <PageHeader eyebrow="Video Studio · Preview" title="Your stories," accent="in motion." description="The media model, long-running job states, thumbnails, previews, and publishing contracts are ready. Provider generation is intentionally gated until a video connector is enabled." actions={<Link href="/providers" className="button secondary"><Icon name="plug" size={16}/>View connectors</Link>}/>
    <section className="video-stage card">
      <div className="stage-copy"><StatusBadge status="Backend ready"/><h2>Prompt-to-video is the next canvas.</h2><p>Compose around duration, aspect ratio, motion strength, frame rate, and reference assets—with the same library and publishing workflow used for images.</p><button className="button" disabled><Icon name="video" size={17}/>Generation coming soon</button></div>
      <div className="stage-visual"><span className="video-frame one"/><span className="video-frame two"/><div className="play-button"><Icon name="video" size={25}/></div><div className="timeline"><span/><i/><i/><i/></div></div>
    </section>
    <div className="readiness-grid"><article className="card"><span><Icon name="wand"/></span><b>Prompt to motion</b><p>Duration, aspect ratio, motion strength, and reference assets already map cleanly to provider settings.</p></article><article className="card"><span><Icon name="clock"/></span><b>Progress-aware jobs</b><p>Long-running generation supports provider callbacks, reliable polling, and visible progress states.</p></article><article className="card"><span><Icon name="image"/></span><b>Preview-ready assets</b><p>Video metadata includes thumbnails, preview URLs, duration, frame rate, and transcode status.</p></article><article className="card"><span><Icon name="send"/></span><b>Publishing contract</b><p>Social connectors expose video publishing methods while the production UI remains safely disabled.</p></article></div>
    <section className="video-roadmap card"><div><p className="eyebrow">Activation path</p><h2>What unlocks the studio</h2></div><ol><li><span>01</span><p><b>Enable a video provider</b><small>Configure Runway, Kling, Veo, fal.ai, or another adapter.</small></p><Icon name="check"/></li><li><span>02</span><p><b>Validate job callbacks</b><small>Verify progress, completion, failure, and cancellation events.</small></p><Icon name="clock"/></li><li><span>03</span><p><b>Turn on generation</b><small>Expose the composer only after provider and cost controls are ready.</small></p><Icon name="arrow"/></li></ol></section>
  </div><style>{`
    .video-page{background:radial-gradient(circle at 70% 22%,rgba(61,147,178,.07),transparent 22rem)}.video-page .page-header h1 em{color:#a4eaff}.video-stage{display:grid;grid-template-columns:.83fr 1.17fr;min-height:430px;overflow:hidden;border-color:rgba(119,220,247,.14)}.stage-copy{display:grid;align-content:center;justify-items:start;gap:17px;padding:42px}.stage-copy h2{margin:0;font-size:30px;line-height:1.06;letter-spacing:-.04em}.stage-copy p{margin:0;color:var(--muted);font-size:11px;line-height:1.65}.stage-visual{position:relative;display:grid;place-items:center;overflow:hidden;background:radial-gradient(circle at 65% 32%,rgba(90,204,232,.23),transparent 13rem),linear-gradient(145deg,#12232d,#090d12)}.video-frame{position:absolute;width:58%;aspect-ratio:16/10;border:1px solid rgba(119,220,247,.16);border-radius:18px;background:linear-gradient(145deg,rgba(119,220,247,.08),rgba(155,122,255,.05));transform:rotate(-8deg) translate(-28px,-10px);box-shadow:0 20px 50px #0005}.video-frame.two{transform:rotate(8deg) translate(36px,20px);opacity:.6}.play-button{position:relative;z-index:2;display:grid;place-items:center;width:72px;height:72px;border:1px solid rgba(255,255,255,.22);border-radius:50%;background:rgba(119,220,247,.92);color:#061117;box-shadow:0 18px 45px rgba(72,190,220,.25)}.timeline{position:absolute;right:9%;bottom:14%;left:9%;display:grid;grid-template-columns:1fr auto auto auto;gap:7px;align-items:center}.timeline>span{height:4px;border-radius:99px;background:linear-gradient(90deg,var(--cyan) 38%,rgba(255,255,255,.14) 38%)}.timeline i{width:5px;height:5px;border-radius:50%;background:rgba(255,255,255,.22)}.readiness-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:14px}.readiness-grid article{display:grid;gap:10px;padding:17px}.readiness-grid article>span{display:grid;place-items:center;width:38px;height:38px;border-radius:11px;background:rgba(119,220,247,.07);color:var(--cyan)}.readiness-grid b{font-size:11px}.readiness-grid p{margin:0;color:var(--muted);font-size:9px;line-height:1.55}.video-roadmap{display:grid;grid-template-columns:.65fr 1.35fr;gap:30px;margin-top:14px;padding:24px}.video-roadmap h2{margin:0;font-size:24px}.video-roadmap ol{display:grid;gap:0;margin:0;padding:0;list-style:none}.video-roadmap li{display:grid;grid-template-columns:auto 1fr auto;gap:12px;align-items:center;padding:12px 0;border-bottom:1px solid var(--line)}.video-roadmap li:last-child{border:0}.video-roadmap li>span{color:var(--cyan);font-size:9px;font-weight:900}.video-roadmap li p{display:grid;gap:3px;margin:0}.video-roadmap li b{font-size:10px}.video-roadmap li small{color:var(--muted);font-size:9px}.video-roadmap li>svg{color:var(--muted-2)}
    @media(max-width:1050px){.video-stage{grid-template-columns:1fr}.stage-visual{min-height:330px}.readiness-grid{grid-template-columns:1fr 1fr}}@media(max-width:650px){.stage-copy{padding:26px 20px}.stage-copy h2{font-size:24px}.stage-visual{min-height:270px}.readiness-grid{grid-template-columns:1fr}.video-roadmap{grid-template-columns:1fr;padding:19px}}
  `}</style></main>;
}
