from dataclasses import dataclass
from typing import Protocol
@dataclass(frozen=True)
class ImageRequest: prompt:str;style_preset:str;aspect_ratio:str;output_count:int
@dataclass(frozen=True)
class GeneratedImage: content:bytes;mime_type:str;width:int;height:int;provider_metadata:dict
class BaseMediaProvider(Protocol):
 name:str
 def generate_image(self,request:ImageRequest)->list[GeneratedImage]: ...
 def edit_image(self,image_url:str,prompt:str,settings:dict)->GeneratedImage: ...
 def upscale_image(self,image_url:str,settings:dict)->GeneratedImage: ...
 def generate_video(self,prompt:str,settings:dict)->object: ...
