from dataclasses import dataclass
from typing import Protocol
@dataclass(frozen=True)
class ImageRequest: prompt:str;style_preset:str;aspect_ratio:str;output_count:int
@dataclass(frozen=True)
class GeneratedImage: content:bytes;mime_type:str;width:int;height:int;provider_metadata:dict
@dataclass(frozen=True)
class VideoRequest: prompt:str;duration_seconds:int;fps:int;aspect_ratio:str;motion_strength:float;reference_asset_ids:list[str]
class BaseMediaProvider(Protocol):
 name:str
 def generate_image(self,request:ImageRequest)->list[GeneratedImage]: ...
 def edit_image(self,image_url:str,prompt:str,settings:dict)->GeneratedImage: ...
 def upscale_image(self,image_url:str,settings:dict)->GeneratedImage: ...
 def generate_video(self,request:VideoRequest)->dict: ...
 def get_job_status(self,external_job_id:str)->dict: ...
